import Head from 'next/head'
import Link from 'next/link';

// importing apis
import { popularGamesUrl } from '../../components/game/api'

export default function Home() {
 
  return (
    <div className='font-poppins'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"  />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;1,300&display=swap" rel="stylesheet" /> 

      </Head>

      <div className="flex flex-col min-h-[100vh] w-full justify-center items-center text-white bg-[#04003a]">
        <Link href='/games/popular'>
          <a className='text-[2rem] hover:underline transition-all '>Popular Games</a>
        </Link>
        <Link href='/games/upcoming'>
          <a className='py-[3rem] text-[2rem] hover:underline transition-all'>Upcoming Games</a>
        </Link>
        <Link href='/games/new'>
          <a className='text-[2rem] hover:underline transition-all'>New Games</a>
        </Link>
      </div>
    </div>
  )
}


